name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    name: CmakeWithBoost
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Configure
      shell: bash
      run: mkdir build && cmake -S . -B ./build
    
    - name: Build
      shell: bash
      run: cmake --build ./build --config Release    

